### PR TITLE
move icinga features in definiton

### PR DESCRIPTION
**Pull request by scopenco**
some times we need to customize templates for icinga2 features like ido-mysql, api, etc. This patch allow to deploy template source from custom cookbook and customize feature list.

### CODE REVIEW

**Comment by vkhatri** [comment]
@scopenco LWRP is more preferable and adopted over definitions, it also helps cookbook to keep a standard resource create methodology.

Features are default icinga2 objects configuration files linked to include directory when enabled. 

How about creating icinga2 object using LWRP resource instead for managing feature objects config files? IMHO, it is a better way than managing default conf files. Cookbook contains LWRP for almost every icinga2 object.

However, recipe `icinga2::server_features` & node attribute `node['icinga2']['enable_features']` will be deprecated in favor of LWRP `feature` in next release.

Let me know if it helps.

**Comment by scopenco** [comment]
if i will use LWRP, cmd will show me
```bash
iicinga2 feature list
critical/cli: Cannot access path .
```
that mean icinga2 tools don't understand that object is loaded and using command line i cant get list of enabled modules

**Comment by vkhatri** [comment]
@scopenco are you using LWRP `feature`? LWRP `feature` does not execute command `list`, so i do not know where exactly you are getting this error. 

would you be able to share your wrapper recipe? to see what are you trying to do.

**Comment by scopenco** [comment]
yes, i'm using LWRPs like 

icinga2_checkercomponent 'checkercomponent'
icinga2_compatlogger 'compatlogger'
icinga2_livestatuslistener 'livestatuslistener'
icinga2_filelogger 'filelogger' do
  severity 'information'
  path "#{node['icinga2']['log_dir']}/icinga2.log"
end

converge is ok, and new files created in /etc/icinga2/objects.d/
but console command
```bash
icinga2 feature list
```
show me 
```
critical/cli: Cannot access path ''.
```
because /etc/icinga2/features-available /etc/icinga2/features-enabled path hardcoded in icinga2 binary.
```
setuid(496)                             = 0
open("/etc/icinga2/features-available", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
gettimeofday({1422700708, 653198}, NULL) = 0
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f7e357d9000
write(1, "\33[31m\33[1mcritical\33[0m/cli: Canno"..., 50critical/cli: Cannot access path ''.
) = 50
```

**Comment by vkhatri** [comment]
@scopenco this does not look like related to this PR or LWRP `feature` as i see that you are not using it.

Though none of the LWRP you are using alter any path or variable which could have caused this error. As `"/etc/icinga2/features-available"` is hard coded it should not have any impact on icinga2 configuration, strange.

i will try to reproduce your scenario.

**Comment by vkhatri** [comment]
@scopenco there were typos in LWRP compatlogger & livestatuslistener, i have fixed them.

But, i am unable to reproduce the error you are seeing. 

Could you once purge directory `object.d` and restart icinga2 to see whether you still see the error.

**Comment by vkhatri** [comment]
@scopenco were you able to figure out the issue? i do not think this PR is required anymore.

**Comment by scopenco** [comment]
let me explain you in details.
icinga2 binary can list loaded modules with command:
```bash
/usr/sbin/icinga2 feature list
```
icinga2 look in /etc/icinga2/features-enabled/ and /etc/icinga2/features-available/ and check symlinks.
If i create feature object with LWRP in /etc/icinga2/objects.d/, and remove all symlinks in /etc/icinga2/features-enabled/, then "icinga2 feature list" show
```
icinga2 feature list
critical/cli: Cannot access path ''.
```
but modules loading in /etc/icinga2/objects.d/

I think that my pull request resolve this problem correctly and for "features" LWPR is not usable because the should create confiigs and symlinks in  /etc/icinga2/features-available/  and  /etc/icinga2/features-enabled/, not in object.d

**Comment by vkhatri** [comment]
@scopenco i do not see how that is the problem. If you disable all features, that is the expected behavior of `/usr/sbin/icinga2 feature list` which is not related to LWRP `feature` or this cookbook.

Regarding this PR, features are nothing but another icinga2 object conf files. This cookbook offers LWRP to manage icinga2 objects rather than managing default conf files / features.

IMHO, there is no need to manage the default conf files, one have a choice either to enable/disable `feature` with default config or create LWRP resource instead.

**Comment by scopenco** [comment]
ok, IMHO cookbook should be compatible with __/usr/sbin/icinga2__ syntax

**Pull request closed without merging**
