### PR TITLE
add test kitchen support

### PR DESCRIPTION
**Pull request by scopenco**
this patch allow to converge cookbook in Test Kitchen. Lets fix all other object the same way.

### CODE REVIEW

**Comment by scopenco** [comment]
any updates?

**Comment by vkhatri** [comment]
@scopenco  will check tomorrow

**Comment by scopenco** [comment]
did you checked?

**Comment by scopenco** [comment]
hi, any updates?

**Comment by vkhatri** [comment]
@scopenco sorry about that, been busy lately. from the glimpse of it, kitchen does not like the method `objects`. i am skeptical about the code change to get kitchen to pass the convergence.

**Comment by scopenco** [comment]
test kitchen right now is the most popular method of cookbook testing. I dont understand why you are not agree to adopt version to test kitchen. i'm ready to create pull requests for this.

**Comment by legal90** [comment]
@vkhatri This error is not related to `test-kitchen` overall. It is reproduced on Chef Client 12.0.3.
So, this is a Chef syntax error, meaning that ruby code (and method calls in particular) should not be placed to value of resource's attribute.
The similar problem: http://stackoverflow.com/questions/15743546/chef-create-template-with-dynamic-variable

Method's name doesn't make sense, and there are two way to fix that:
1) To avoid method calls in the resource's attribute (like @scopenco have suggested in this pull-request)
2) Either just use "Lazy attribute evaluation" 
https://docs.chef.io/resource_common.html#lazy-attribute-evaluation

Please, fix it by whatever you like.

P.s. By the way, what do you think about enabling 'Issues' in this repo? It will be very useful for issue reporting. Thanks!

**Comment by dnsmichi** [comment]
Issues should be reported to dev.icinga.org where all Icinga developers organize their tasks. We won't enable a secondary issue tracker here, sorry.

https://dev.icinga.org/projects/chef-icinga2

**Comment by vkhatri** [comment]
@scopenco i am not oppose to fixing kitchen test. it make more sense now to know that it causes issue with Chef 12.x. this cookbook is not yet tested for Chef 12. @legal90 thanks for pointing the issue.

**Pull request merged**
