### PR TITLE
add array of plugins to icinga2.conf

### PR DESCRIPTION
**Pull request by scopenco**
add support of node['icinga2']['include_itl'] discussed in https://github.com/Icinga/chef-icinga2/pull/9/commits

### CODE REVIEW

**Comment by vkhatri** [comment]
could you re base the PR? seems to have early commits no longer required

**Comment by scopenco** [comment]
@vkhatri done

**Comment by vkhatri** [comment]
@scopenco unfortunately i can still see the commit history. file changes looks good, except `manubulon` itl is not by default included in `icinga2.conf`.

**Comment by scopenco** [comment]
@vkhatri i have removed manubulon from default include_itl list

**Comment by vkhatri** [comment]
@scopenco thanks, what i meant by i can still see historic commit is that in a PR only targeted changes should be submitted, commits to revert commits or commits to update previous commits in PR should not be part of a PR.

**Comment by scopenco** [comment]
@vkhatri  rebase done, is this enough?

**Comment by vkhatri** [comment]
@scopenco sorry if i gave away a wrong impression. IMHO, i expect only one commit (https://github.com/parallels-cookbooks/chef-icinga2/commit/fc194eedc5b38d4f9f3e3d26f7e9152f4c173fe6)  in the PR for adding new attribute and template update, i am afraid this PR will not look good in commit history.

could you please squash commit history of this PR in the favor of keeping commit history clean. let me know.

**Pull request closed without merging**
