### PR TITLE
Bug #9900 - icinga2 classic ui user creation doc and code out of sync

### PR DESCRIPTION
**Pull request by saurabh-hirani**
Details - https://dev.icinga.org/issues/9900

### CODE REVIEW

**Comment by saurabh-hirani** [comment]
An feedback/update on this?

**Comment by boldandbusted** [comment]
There is some feedback for you, @saurabh-hirani, in the Bug #9900, FYI.

**Comment by saurabh-hirani** [comment]
My bad - was on another task for a while. Will check it out. Thanks.

**Comment by vkhatri** [comment]
closing, updated icinga issue.

**Pull request closed without merging**
